import type { ClassSpec } from '../../engine/types';
import { HUNTER_HOOKS } from './hunter-hooks';

export const HUNTER: ClassSpec = {
  key: 'hunter',
  name: 'Hunter',
  color: '#AAD372',
  icon: '🏹',
  iconImg: 'img/classes/hunter.jpg',

  formulas: {
    hp: (s, lvl) => 35 + s.aguante * 9 + lvl * 5,
    mana: () => 0,
    spellPower: () => 0,
    attackPower: s => s.agilidad * 2,
    manaRegen: () => 0,
  },

  baseStats: { fuerza: 10, agilidad: 25, intelecto: 6, aguante: 19, espiritu: 12 },
  startingLevel: 1,
  statGrowth: { fuerza: 0.4, agilidad: 2.2, intelecto: 0.1, aguante: 1.3, espiritu: 0.3 },
  armor: 8,
  magicResist: 2,

  resource: { type: 'focus', label: 'Focus', color: '#aad372', max: 100, start: 'full', regen: 0 },

  talents: [
    {
      id: 'ranged_weapon_spec',
      name: 'Ranged Weapon Specialization',
      icon: '🏹',
      iconImg: 'img/talents/hunter/ranged_weapon_spec.jpg',
      description: 'Aumenta el daño de Auto Shot, Arcane Shot, Aimed Shot y Multi-Shot un 2% por punto.',
      maxRank: 3,
      tier: 1,
      requires: null,
      modifiers: [{ target: 'ability:auto_shot|arcanic_shot|aimed_shot|multi_shot', stat: 'damage', type: 'pct', valuePerRank: 2 }],
    },
    {
      id: 'bestial_discipline',
      name: 'Bestial Discipline',
      icon: '🐺',
      iconImg: 'img/talents/hunter/bestial_discipline.jpg',
      description: 'Aumenta el daño de los ataques básicos de tu pet un 10% por punto y el Focus que generan en +2/+4/+5.',
      maxRank: 3,
      tier: 1,
      requires: null,
      modifiers: [],
    },
    {
      id: 'improved_aspect_of_the_hawk',
      name: 'Improved Aspect of the Hawk',
      icon: '🦅',
      iconImg: 'img/talents/hunter/improved_aspect_of_the_hawk.jpg',
      description: 'Mientras Aspect of the Hawk está activo, +4% por punto de probabilidad de crítico para tus ataques a distancia.',
      maxRank: 3,
      tier: 1,
      requires: null,
      modifiers: [
        {
          target: 'tag:ranged',
          stat: 'critChance',
          type: 'flat',
          valuePerRank: 4,
          conditions: [{ kind: 'casterHasEffect', name: 'Aspect of the Hawk' }],
        },
      ],
    },
    {
      id: 'survivalist',
      name: 'Survivalist',
      icon: '❤️',
      iconImg: 'img/talents/hunter/survivalist.jpg',
      description: 'Aumenta tu vida máxima un 3% por punto.',
      maxRank: 3,
      tier: 1,
      requires: null,
      modifiers: [{ target: '*', stat: 'maxHP', type: 'pct', valuePerRank: 3 }],
    },
    {
      id: 'serpent_spread',
      name: 'Serpent Spread',
      icon: '🐍',
      iconImg: 'img/talents/hunter/serpent_spread.jpg',
      description: 'Multi-Shot aplica Serpent Sting a todos los enemigos con una efectividad del 15% por punto de su daño normal.',
      maxRank: 4,
      tier: 2,
      requires: null,
      modifiers: [],
    },
    {
      id: 'improved_kill_command',
      name: 'Improved Kill Command',
      icon: '🐾',
      iconImg: 'img/talents/hunter/improved_kill_command.jpg',
      description: 'Reduce el cooldown de Kill Command en 1 turno por punto.',
      maxRank: 2,
      tier: 2,
      requires: null,
      modifiers: [],
    },
    {
      id: 'improved_hunters_mark',
      name: "Improved Hunter's Mark",
      icon: '🎯',
      iconImg: 'img/talents/hunter/improved_hunters_mark.jpg',
      description: "Aumenta la reducción de Armor de Hunter's Mark un 10% por punto.",
      maxRank: 3,
      tier: 2,
      requires: null,
      modifiers: [],
    },
    {
      id: 'improved_aimed_shot',
      name: 'Improved Aimed Shot',
      icon: '🎯',
      iconImg: 'img/talents/hunter/improved_aimed_shot.jpg',
      description: 'Reduce el coste de Aimed Shot en 5 Focus por punto.',
      maxRank: 3,
      tier: 2,
      requires: null,
      modifiers: [{ target: 'ability:aimed_shot', stat: 'focusCost', type: 'flat', valuePerRank: -5 }],
    },
    {
      id: 'double_tap',
      name: 'Double Tap',
      icon: '✨',
      iconImg: 'img/talents/hunter/double_tap.jpg',
      description: 'Arcane Shot tiene un 15% por punto de probabilidad de dispararse una segunda vez gratis (mismo daño, genera focus).',
      maxRank: 3,
      tier: 3,
      requires: null,
      modifiers: [],
    },
    {
      id: 'mortal_shots',
      name: 'Mortal Shots',
      icon: '💀',
      iconImg: 'img/talents/hunter/mortal_shots.jpg',
      description: 'Aumenta el daño de los críticos de tus disparos un 5% por punto.',
      maxRank: 3,
      tier: 3,
      requires: null,
      modifiers: [{ target: 'tag:ranged', stat: 'critDamage', type: 'pct', valuePerRank: 5 }],
    },
    {
      id: 'ferocious_inspiration',
      name: 'Ferocious Inspiration',
      icon: '🦁',
      iconImg: 'img/talents/hunter/ferocious_inspiration.jpg',
      description: 'Mejora tus pets: Furious Howl también beneficia a toda la party (1 punto = 50% efectividad = +5% Attack Power, 2 puntos = 100% = +10%); Growl da Thick Skin al Bear (+8/+15 Armor) 3 turnos.',
      maxRank: 2,
      tier: 3,
      requires: null,
      modifiers: [],
    },
    {
      id: 'lock_and_load',
      name: 'Lock and Load',
      icon: '🧨',
      iconImg: 'img/talents/hunter/lock_and_load.jpg',
      description: 'Después de utilizar Frost Trap, tienes un 35%/70%/100% de probabilidad de que tu siguiente Aimed Shot se convierta en Instant y solo consuma 1 acción.',
      maxRank: 3,
      tier: 3,
      requires: null,
      modifiers: [],
    },
  ],

  capstones: [
    { id: 'lone_wolf', name: 'Lone Wolf', icon: '🐺', iconImg: 'img/capstones/hunter/lone_wolf.jpg', description: 'No puedes tener un pet activo durante el resto del combate. Tienes 1 acción adicional por turno.' },
    { id: 'explosive_shot', name: 'Explosive Shot', icon: '💥', iconImg: 'img/capstones/hunter/explosive_shot.jpg', description: 'Coste: 50 Focus. Cast. Dispara un proyectil que impacta de inmediato con daño de Fuego en área y se incrusta dejando un DOT de Fuego cada turno durante 3 turnos, también en área.' },
    { id: 'animal_companion', name: 'Animal Companion', icon: '🐾', iconImg: 'img/capstones/hunter/animal_companion.jpg', description: 'Invoca Wolf y Bear a la vez. Ambos atacan, usan sus habilidades y generan Focus por separado.' },
  ],

  abilities: [
    {
      id: 'basic_attack',
      name: 'Basic Attack',
      icon: '🎯',
      iconImg: 'img/abilities/hunter/basic_attack.jpg',
      school: 'Físico',
      type: 'damage',
      requiredLevel: 1,
      damageType: 'physical',
      baseDamage: 0,
      spellPowerRatio: 0,
      costPct: 0,
      costFocus: 0,
      castType: 'instant',
      cooldown: 0,
      description: 'Un ataque básico con tu arma que no gasta focus.',
      tags: ['physical', 'direct'],
      usesWeaponDamage: true,
    },
    {
      id: 'auto_shot',
      name: 'Auto Shot',
      icon: '🏹',
      iconImg: 'img/abilities/hunter/auto_shot.jpg',
      school: 'Físico',
      type: 'damage',
      requiredLevel: 1,
      damageType: 'physical',
      baseDamage: 0,
      spellPowerRatio: 0,
      costPct: 0,
      costFocus: 0,
      focusGain: 5,
      castType: 'instant',
      cooldown: 0,
      description: 'Disparo básico con tu arma que genera 5 Focus. No tiene rangos: escala solo con el arma.',
      tags: ['physical', 'direct', 'ranged'],
      usesWeaponDamage: true,
    },
    {
      id: 'arcanic_shot',
      name: 'Arcane Shot',
      icon: '✨',
      iconImg: 'img/abilities/hunter/arcanic_shot.jpg',
      school: 'Arcano',
      type: 'damage',
      requiredLevel: 4,
      damageType: 'magical',
      baseDamage: 1,
      spellPowerRatio: 0,
      costPct: 0,
      costFocus: 0,
      focusGain: 10,
      castType: 'instant',
      cooldown: 2,
      description: 'Dispara un proyectil arcano: 50% del daño de tu arco + 50% del daño Arcano plano, y genera 10 Focus. CD 2.',
      tags: ['direct', 'ranged'],
      damageRanges: [
        { rank: 1, level: 4, min: 45, max: 60 },
        { rank: 2, level: 12, min: 85, max: 110 },
        { rank: 3, level: 20, min: 140, max: 175 },
        { rank: 4, level: 28, min: 210, max: 260 },
      ],
    },
    {
      id: 'aimed_shot',
      name: 'Aimed Shot',
      icon: '🎯',
      iconImg: 'img/abilities/hunter/aimed_shot.jpg',
      school: 'Físico',
      type: 'damage',
      requiredLevel: 6,
      damageType: 'physical',
      baseDamage: 1,
      spellPowerRatio: 0,
      costPct: 0,
      costFocus: 60,
      castType: 'cast',
      cooldown: 0,
      description: 'Dispara con cuidado apuntado: daño físico elevado (suma el arma). Cuesta 60 Focus.',
      tags: ['physical', 'direct', 'ranged'],
      damageRanges: [
        { rank: 1, level: 6, min: 100, max: 130 },
        { rank: 2, level: 14, min: 180, max: 230 },
        { rank: 3, level: 22, min: 300, max: 370 },
        { rank: 4, level: 30, min: 460, max: 560 },
      ],
    },
    {
      id: 'multi_shot',
      name: 'Multi-Shot',
      icon: '🌪️',
      iconImg: 'img/abilities/hunter/multi_shot.jpg',
      school: 'Físico',
      type: 'damage',
      requiredLevel: 10,
      damageType: 'physical',
      baseDamage: 1,
      spellPowerRatio: 0,
      costPct: 0,
      costFocus: 30,
      castType: 'instant',
      cooldown: 3,
      aoe: true,
      description: 'Dispara proyectiles a todos los enemigos infligiendo daño físico (suma el arma). Cuesta 30 Focus. CD 3.',
      tags: ['physical', 'direct', 'ranged', 'aoe'],
      damageRanges: [
        { rank: 1, level: 10, min: 30, max: 42 },
        { rank: 2, level: 18, min: 55, max: 72 },
        { rank: 3, level: 26, min: 90, max: 115 },
      ],
      weaponMultiplier: 1.0,
    },
    {
      id: 'serpent_sting',
      name: 'Serpent Sting',
      icon: '🐍',
      iconImg: 'img/abilities/hunter/serpent_sting.jpg',
      school: 'Naturaleza',
      type: 'damage',
      requiredLevel: 8,
      damageType: 'magical',
      baseDamage: 1,
      spellPowerRatio: 0,
      costPct: 0,
      costFocus: 10,
      castType: 'instant',
      cooldown: 3,
      isDot: true,
      dotDuration: 4,
      dotScales: true,
      description: 'Envenena al objetivo: daño de Naturaleza durante 4 turnos. Cuesta 10 Focus. CD 3.',
      tags: ['dot', 'ranged'],
      dotRanges: [
        { rank: 1, level: 8, value: 64, duration: 4 },
        { rank: 2, level: 16, value: 112, duration: 4 },
        { rank: 3, level: 24, value: 180, duration: 4 },
        { rank: 4, level: 32, value: 280, duration: 4 },
      ],
      damageRanges: [
        { rank: 1, level: 8, min: 64, max: 64 },
        { rank: 2, level: 16, min: 112, max: 112 },
        { rank: 3, level: 24, min: 180, max: 180 },
        { rank: 4, level: 32, min: 280, max: 280 },
      ],
    },
    {
      id: 'kill_command',
      name: 'Kill Command',
      icon: '🐾',
      iconImg: 'img/abilities/hunter/kill_command.jpg',
      school: 'Físico',
      type: 'utility',
      requiredLevel: 12,
      costPct: 0,
      costFocus: 0,
      focusGain: 15,
      castType: 'instant',
      cooldown: 3,
      description: 'Ordena a tu pet atacar al objetivo con un golpe extra. Genera 15 Focus y el ataque extra del pet da 10 Focus más. CD 3.',
      tags: ['pet'],
    },
    {
      id: 'disengage',
      name: 'Disengage',
      icon: '💨',
      iconImg: 'img/abilities/hunter/disengage.jpg',
      school: 'Físico',
      type: 'utility',
      requiredLevel: 6,
      costPct: 0,
      costFocus: 0,
      focusGain: 5,
      castType: 'instant',
      cooldown: 3,
      noGcd: true,
      description: 'Saltas hacia atrás alejándote del enemigo: +5 Focus, +20% esquivar 1 turno y no gasta acción. CD 3.',
    },
    {
      id: 'hunters_mark',
      name: "Hunter's Mark",
      icon: '🎯',
      iconImg: 'img/abilities/hunter/hunters_mark.jpg',
      school: 'Físico',
      type: 'utility',
      requiredLevel: 2,
      damageType: 'physical',
      baseDamage: 0,
      spellPowerRatio: 0,
      costPct: 0,
      costFocus: 5,
      castType: 'instant',
      cooldown: 0,
      description: 'Marca al objetivo 5 turnos reduciendo su Armor. Cuesta 5 Focus.',
      buff: { stat: 'armor', duration: 5, applySelf: false },
      buffRanks: [
        { rank: 1, level: 2, value: 10 },
        { rank: 2, level: 12, value: 15 },
        { rank: 3, level: 22, value: 20 },
        { rank: 4, level: 30, value: 25 },
      ],
    },
    {
      id: 'frost_trap',
      name: 'Frost Trap',
      icon: '❄️',
      iconImg: 'img/abilities/hunter/frost_trap.jpg',
      school: 'Escarcha',
      type: 'utility',
      requiredLevel: 6,
      damageType: 'magical',
      baseDamage: 0,
      spellPowerRatio: 0,
      costPct: 0,
      costFocus: 10,
      castType: 'instant',
      cooldown: 3,
      aoe: true,
      description: 'Trampa de escarcha que afecta a todos los enemigos reduciendo su capacidad de movimiento: -40% daño 3 turnos. Cuesta 10 Focus. CD 3.',
      buff: { stat: 'attackPower', duration: 3, applySelf: false },
      buffRanks: [
        { rank: 1, level: 6, value: 40 },
        { rank: 2, level: 16, value: 45 },
        { rank: 3, level: 26, value: 50 },
      ],
    },
    {
      id: 'aspect_of_the_hawk',
      name: 'Aspect of the Hawk',
      icon: '🦅',
      iconImg: 'img/abilities/hunter/aspect_of_the_hawk.jpg',
      school: 'Físico',
      type: 'utility',
      requiredLevel: 2,
      costPct: 0,
      costFocus: 5,
      castType: 'instant',
      cooldown: 0,
      description: 'Aumenta tu Attack Power en +20 por rango durante 30 turnos. Solo un Aspect activo. Cuesta 5 Focus.',
      buff: { stat: 'attackPower', duration: 30, applySelf: true },
      buffRanks: [
        { rank: 1, level: 2, value: 20 },
        { rank: 2, level: 12, value: 40 },
        { rank: 3, level: 22, value: 60 },
        { rank: 4, level: 32, value: 80 },
      ],
    },
    {
      id: 'aspect_of_the_monkey',
      name: 'Aspect of the Monkey',
      icon: '🐒',
      iconImg: 'img/abilities/hunter/aspect_of_the_monkey.jpg',
      school: 'Físico',
      type: 'utility',
      requiredLevel: 8,
      costPct: 0,
      costFocus: 5,
      castType: 'instant',
      cooldown: 0,
      description: 'Aumenta tu Dodge +6% y +2% por rango durante 30 turnos. Solo un Aspect activo. Cuesta 5 Focus.',
      buff: { stat: 'evasion', duration: 30, applySelf: true },
      buffRanks: [
        { rank: 1, level: 8, value: 6 },
        { rank: 2, level: 18, value: 8 },
        { rank: 3, level: 28, value: 10 },
        { rank: 4, level: 38, value: 12 },
      ],
    },
    {
      id: 'summon_wolf',
      name: 'Summon Wolf',
      icon: '🐺',
      iconImg: 'img/abilities/hunter/summon_wolf.jpg',
      school: 'Invocación',
      type: 'utility',
      requiredLevel: 4,
      costPct: 0,
      costFocus: 15,
      castType: 'cast',
      cooldown: 0,
      description: 'Invoca un Wolf que lucha a tu lado: ataca cada turno y genera 5 Focus. Puede usar Furious Howl. Un solo pet activo. Cuesta 15 Focus.',
      tags: ['pet'],
      isPetSummon: 'wolf',
    },
    {
      id: 'summon_bear',
      name: 'Summon Bear',
      icon: '🐻',
      iconImg: 'img/abilities/hunter/summon_bear.jpg',
      school: 'Invocación',
      type: 'utility',
      requiredLevel: 10,
      costPct: 0,
      costFocus: 15,
      castType: 'cast',
      cooldown: 0,
      description: 'Invoca un Bear tanque que lucha a tu lado: ataca cada turno y genera 5 Focus. Puede usar Growl. Un solo pet activo. Cuesta 15 Focus.',
      tags: ['pet'],
      isPetSummon: 'bear',
    },
    {
      id: 'furious_howl',
      name: 'Furious Howl',
      icon: '🐺',
      iconImg: 'img/abilities/hunter/furious_howl.jpg',
      school: 'Bestial',
      type: 'utility',
      requiredLevel: 4,
      costPct: 0,
      castType: 'instant',
      cooldown: 3,
      description: 'El Wolf aúlla: Attack Power del Hunter +10%, daño del Wolf y de Kill Command +10% durante 3 turnos. CD 3.',
      tags: ['pet'],
      petAbility: 'wolf',
      buffRanks: [{ rank: 1, level: 4, value: 10 }],
      buff: { stat: 'attackPower', duration: 3, applySelf: true, isPercent: true },
    },
    {
      id: 'growl',
      name: 'Growl',
      icon: '🐻',
      iconImg: 'img/abilities/hunter/growl.jpg',
      school: 'Bestial',
      type: 'utility',
      requiredLevel: 10,
      costPct: 0,
      castType: 'instant',
      cooldown: 0,
      description: 'El Bear gruñe obligando al enemigo a atacarle durante 3 turnos.',
      tags: ['pet'],
      petAbility: 'bear',
      buffRanks: [{ rank: 1, level: 10, value: 3 }],
      buff: { stat: 'growl', duration: 3, applySelf: true },
    },
    {
      id: 'explosive_shot',
      name: 'Explosive Shot',
      icon: '💥',
      iconImg: 'img/capstones/hunter/explosive_shot.jpg',
      school: 'Fuego',
      type: 'utility',
      requiredLevel: 0,
      costPct: 0,
      costFocus: 50,
      castType: 'cast',
      cooldown: 3,
      description: 'Coste: 50 Focus. Dispara un proyectil que impacta de inmediato con daño de Fuego en área y se incrusta dejando un DOT de Fuego cada turno durante 3 turnos, también en área. CD 3.',
      tags: ['aoe', 'dot'],
      capstoneGate: 'explosive_shot',
      isDot: true,
      dotDuration: 3,
      damageRanges: [
        { rank: 1, level: 1, min: 54, max: 84 },
        { rank: 2, level: 20, min: 96, max: 138 },
        { rank: 3, level: 40, min: 150, max: 204 },
      ],
      damageType: 'magical',
    },
  ],

  pets: [
    {
      id: 'wolf',
      name: 'Wolf',
      icon: '🐺',
      iconImg: 'img/abilities/hunter/summon_wolf.jpg',
      requiredLevel: 4,
      hpPct: 0.45,
      manaPct: 0,
      attackName: 'Bite',
      attackMin: 18,
      attackMax: 28,
      attackSchool: 'Físico',
      manaCostPct: 0,
      focusGain: 5,
    },
    {
      id: 'bear',
      name: 'Bear',
      icon: '🐻',
      iconImg: 'img/abilities/hunter/summon_bear.jpg',
      requiredLevel: 10,
      hpPct: 0.7,
      manaPct: 0,
      attackName: 'Claw',
      attackMin: 16,
      attackMax: 24,
      attackSchool: 'Físico',
      manaCostPct: 0,
      focusGain: 5,
    },
  ],

  hooks: HUNTER_HOOKS,
};
