import type { ClassSpec } from '../../engine/types';
import { WARLOCK_HOOKS } from './warlock-hooks';

export const WARLOCK: ClassSpec = {
  key: 'warlock',
  name: 'Warlock',
  color: '#8B2DF0',
  icon: '😈',
  iconImg: 'img/classes/warlock.jpg',

  formulas: {
    hp: (s, lvl) => 30 + s.aguante * 9 + lvl * 5,
    mana: (s, lvl) => 40 + s.intelecto * 15 + lvl * 5,
    spellPower: s => Math.round(s.intelecto * 0.65),
    attackPower: () => 0,
    manaRegen: s => Math.round(s.espiritu * 0.25 + 12),
  },

  baseStats: { fuerza: 10, agilidad: 10, intelecto: 16, aguante: 14, espiritu: 12 },
  startingLevel: 1,
  statGrowth: { intelecto: 2.0, aguante: 1.8, espiritu: 0.8, fuerza: 0.3, agilidad: 0.3 },
  armor: 8,
  magicResist: 3,

  resource: { type: 'mana', label: 'Mana', color: '#9b59b6', start: 'full' },
  comboConfig: { label: 'Soul Shards', icon: '🔮', max: 5 },

  talents: [
    {
      id: 'pocket_shards',
      name: 'Pocket Shards',
      icon: '🔮',
      iconImg: 'img/talents/warlock/pocket_shards.jpg',
      description: 'Por punto: tras un descanso mantienes 1 Soul Shard y aumentas tu maximo de Soul Shards en 1.',
      maxRank: 2,
      tier: 1,
      requires: null,
      modifiers: [{ target: '*', stat: 'maxShards', type: 'flat', valuePerRank: 1 }],
    },
    {
      id: 'improved_drain_life',
      name: 'Improved Drain Life',
      icon: '🩸',
      iconImg: 'img/abilities/warlock/Spell_Shadow_LifeDrain02.jpg',
      description: 'Aumenta la vida que cura Drain Life un 10% por punto. Solo afecta a la curacion, no al dano.',
      maxRank: 3,
      tier: 1,
      requires: null,
      modifiers: [],
    },
    {
      id: 'demonic_embrace',
      name: 'Improved Fel Armor',
      icon: '😈',
      iconImg: 'img/abilities/warlock/Spell_Shadow_FelArmour.jpg',
      description: 'Mientras Fel Armor este activo, tu vida maxima aumenta un 10% por punto.',
      maxRank: 2,
      tier: 1,
      requires: null,
      modifiers: [
        { target: '*', stat: 'maxHP', type: 'pct', valuePerRank: 10, conditions: [{ kind: 'casterHasEffect', name: 'Fel Armor' }] },
      ],
    },
    {
      id: 'destruction_specialization',
      name: 'Destruction Specialization',
      icon: '💥',
      iconImg: 'img/talents/warlock/destruction_specialization.jpg',
      description: 'Aumenta el dano de los golpes criticos de Chaos Bolt y Rain of Fire un 10% por punto, y su probabilidad de critico un 5% por punto.',
      maxRank: 3,
      tier: 1,
      requires: null,
      modifiers: [
        { target: 'ability:chaos_bolt|rain_of_fire', stat: 'critChance', type: 'flat', valuePerRank: 5 },
        { target: 'ability:chaos_bolt|rain_of_fire', stat: 'critDamage', type: 'pct', valuePerRank: 10 },
      ],
    },
    {
      id: 'dot_master',
      name: 'DoT Master',
      icon: '⏱️',
      iconImg: 'img/talents/warlock/dot_master.jpg',
      description: 'Aumenta la duracion de Corruption, Curse of Agony e Immolate en 1 turno por punto. El danyo por turno se mantiene igual, por lo que el total aumenta.',
      maxRank: 3,
      tier: 2,
      requires: null,
      modifiers: [
        { target: 'ability:corruption|curse_of_agony|immolate', stat: 'dotDuration', type: 'flat', valuePerRank: 1 },
      ],
    },
    {
      id: 'improved_healthstone',
      name: 'Improved Healthstone',
      icon: '💎',
      iconImg: 'img/abilities/warlock/INV_Stone_04.jpg',
      description: 'Healthstone genera un segundo evento "Healthstone (Mejorada)" con un 25% por punto de la curacion. Si la principal cura a un aliado, el master devuelve esa Mejorada al warlock.',
      maxRank: 2,
      tier: 2,
      requires: null,
      modifiers: [],
    },
    {
      id: 'grimoire_of_command',
      name: 'Grimoire of Command',
      icon: '📖',
      iconImg: 'img/talents/warlock/grimoire_of_command.jpg',
      description: 'Fortalece a tus demonios: +25% dano del Imp y +25% vida del Voidwalker por punto. El Taunt del Voidwalker cura un 10% de su vida por punto. Blood Boil del Imp, ademas de su buff de Aguante, sacrifica un 10% de su vida por punto y lanza ese dano en area.',
      maxRank: 3,
      tier: 2,
      requires: null,
      modifiers: [],
    },
    {
      id: 'shadow_mastery',
      name: 'Shadow Mastery',
      icon: '🌑',
      iconImg: 'img/talents/warlock/shadow_mastery.jpg',
      description: 'Aumenta el danyo de Shadow Bolt y Drain Life un 5% por punto.',
      maxRank: 2,
      tier: 2,
      requires: null,
      modifiers: [{ target: 'ability:shadow_bolt|drain_life', stat: 'damage', type: 'pct', valuePerRank: 5 }],
    },
    {
      id: 'soul_conduit',
      name: 'Soul Conduit',
      icon: '🌀',
      iconImg: 'img/talents/warlock/soul_conduit.jpg',
      description: 'Al gastar Soul Shards en un hechizo o habilidad, tienes un 20% por punto de probabilidad de recuperar la Shard. Las invocaciones de demonios no se ven afectadas.',
      maxRank: 3,
      tier: 3,
      requires: null,
      modifiers: [],
    },
    {
      id: 'soul_leech',
      name: 'Soul Leech',
      icon: '🛡️',
      iconImg: 'img/talents/warlock/soul_leech.jpg',
      description: 'Shadow Bolt y Chaos Bolt te curan un 10% por punto del dano infligido (sobre el dano final, incluidos los criticos).',
      maxRank: 2,
      tier: 3,
      requires: null,
      modifiers: [],
    },
    {
      id: 'contagion',
      name: 'Contagion',
      icon: '🦠',
      iconImg: 'img/talents/warlock/contagion.jpg',
      description: 'Aumenta el danyo de todos tus DoTs un 2% por punto.',
      maxRank: 3,
      tier: 3,
      requires: null,
      modifiers: [{ target: 'tag:dot', stat: 'dotDamage', type: 'pct', valuePerRank: 2 }],
    },
    {
      id: 'backdraft',
      name: 'Backdraft',
      icon: '🔥',
      iconImg: 'img/talents/warlock/backdraft.jpg',
      description: 'Immolate se lanza de forma instantanea, sin casteo, y su dano directo aumenta un 15% (el DoT no se ve afectado). Requiere Contagion al maximo.',
      maxRank: 1,
      tier: 3,
      requires: { id: 'contagion', points: 3 },
      modifiers: [{ target: 'ability:immolate', stat: 'directDamage', type: 'pct', valuePerRank: 15 }],
    },
  ],

  capstones: [
    { id: 'summon_infernal', name: 'Summon Infernal', icon: '🔥', iconImg: 'img/capstones/warlock/sumon_infernal.jpg', description: 'Coste: 2 Soul Shards. Invoca un Infernal desde el Twisting Nether. Al aterrizar, inflige daño de Fuego a todos los enemigos cercanos y los aturde durante 1 turno. El Infernal lucha a tu lado durante 4 turnos. Invocar un Infernal no sustituye ni hace desaparecer a tu demonio actual.' },
    { id: 'seed_of_corruption', name: 'Seed of Corruption', icon: '🌱', iconImg: 'img/capstones/warlock/seed_of_corruption.jpg', description: 'Coste: 35% de mana y 1 Soul Shard. Aplica un DoT propio potenciado (Seed of Corruption, +10% danyo) a todos los enemigos. Genera 1 Soul Shard por cada enemigo afectado, hasta un maximo de 5.' },
    { id: 'demonic_sacrifice', name: 'Demonic Sacrifice', icon: '💀', iconImg: 'img/capstones/warlock/demonic_sacrifice.jpg', description: 'Coste: 2 Soul Shards. Sacrificas tu demonio invocado y obtienes un efecto permanente durante el combate: Imp - Burning Soul (+20% Spell Power); Voidwalker - Void Fortitude (+25% vida maxima y escudo instantaneo del 25%). Se pierde al invocar cualquier pet.' },
  ],

  abilities: [
    {
      id: 'shadow_bolt',
      name: 'Shadow Bolt',
      icon: '🌑',
      iconImg: 'img/abilities/warlock/Spell_Shadow_ShadowBolt.jpg',
      school: 'Oscuro',
      type: 'damage',
      requiredLevel: 1,
      damageType: 'magical',
      baseDamage: 20,
      spellPowerRatio: 1.0,
      costPct: 0.08,
      castType: 'cast',
      cooldown: 0,
      description: 'Lanza una descarga de energia oscura. Genera 1 Soul Shard.',
      tags: ['shadow', 'direct', 'afflic'],
      damageRanges: [
        { rank: 1, level: 1, min: 18, max: 26 },
        { rank: 2, level: 8, min: 30, max: 42 },
        { rank: 3, level: 16, min: 50, max: 68 },
        { rank: 4, level: 22, min: 70, max: 95 },
      ],
      generatesShard: 1,
    },
    {
      id: 'chaos_bolt',
      name: 'Chaos Bolt',
      icon: '🔥',
      iconImg: 'img/abilities/warlock/Ability_Warlock_ChaosBolt.jpg',
      school: 'Fuego',
      type: 'damage',
      requiredLevel: 10,
      damageType: 'magical',
      baseDamage: 40,
      spellPowerRatio: 1.0,
      costPct: 0.15,
      castType: 'cast',
      cooldown: 0,
      description: 'Descarga caotica que ignora resistencias. Consume 3 Soul Shards.',
      tags: ['fire', 'direct'],
      damageRanges: [
        { rank: 1, level: 10, min: 80, max: 106 },
        { rank: 2, level: 18, min: 116, max: 152 },
        { rank: 3, level: 24, min: 172, max: 222 },
      ],
      spendsShards: true,
      shardCost: 3,
    },
    {
      id: 'corruption',
      name: 'Corruption',
      icon: '🟢',
      iconImg: 'img/abilities/warlock/corruption.jpg',
      school: 'Oscuro',
      type: 'damage',
      requiredLevel: 4,
      damageType: 'magical',
      baseDamage: 20,
      spellPowerRatio: 0.57,
      costPct: 0.05,
      castType: 'instant',
      cooldown: 0,
      description: 'Corrompe al enemigo con un DoT de sombra durante 5 turnos. Genera 1 Soul Shard.',
      tags: ['dot', 'shadow', 'afflic'],
      isDot: true,
      dotDuration: 5,
      damageRanges: [
        { rank: 1, level: 1, min: 50, max: 50 },
        { rank: 2, level: 8, min: 90, max: 90 },
        { rank: 3, level: 16, min: 150, max: 150 },
        { rank: 4, level: 22, min: 230, max: 230 },
      ],
      dotRanges: [
        { rank: 1, level: 4, value: 10, duration: 5 },
        { rank: 2, level: 10, value: 18, duration: 5 },
        { rank: 3, level: 16, value: 30, duration: 5 },
        { rank: 4, level: 22, value: 46, duration: 5 },
      ],
      generatesShard: 1,
    },
    {
      id: 'immolate',
      name: 'Immolate',
      icon: '🔥',
      iconImg: 'img/abilities/warlock/Spell_Fire_Immolation.jpg',
      school: 'Fuego',
      type: 'damage',
      requiredLevel: 6,
      damageType: 'magical',
      baseDamage: 25,
      spellPowerRatio: 0.57,
      costPct: 0.07,
      castType: 'cast',
      cooldown: 0,
      description: 'Quema al enemigo causando danyo directo y un DoT de fuego durante 3 turnos. Genera 1 Soul Shard.',
      tags: ['dot', 'fire', 'direct', 'afflic'],
      isDot: true,
      dotDuration: 3,
      damageRanges: [
        { rank: 1, level: 6, min: 20, max: 30 },
        { rank: 2, level: 12, min: 35, max: 50 },
        { rank: 3, level: 18, min: 55, max: 75 },
        { rank: 4, level: 24, min: 85, max: 115 },
      ],
      dotRanges: [
        { rank: 1, level: 6, value: 7, duration: 3 },
        { rank: 2, level: 12, value: 12, duration: 3 },
        { rank: 3, level: 18, value: 18, duration: 3 },
        { rank: 4, level: 24, value: 28, duration: 3 },
      ],
      generatesShard: 1,
    },
    {
      id: 'curse_of_agony',
      name: 'Curse of Agony',
      icon: '💀',
      iconImg: 'img/abilities/warlock/Spell_Shadow_CurseOfSargeras.jpg',
      school: 'Oscuro',
      type: 'damage',
      requiredLevel: 8,
      damageType: 'magical',
      baseDamage: 15,
      spellPowerRatio: 0.57,
      costPct: 0.04,
      castType: 'instant',
      cooldown: 0,
      description: 'Maldicion que causa un DoT creciente durante 6 turnos. Consume 1 Soul Shard.',
      tags: ['dot', 'shadow', 'afflic'],
      isDot: true,
      dotDuration: 6,
      damageRanges: [
        { rank: 1, level: 8, min: 66, max: 66 },
        { rank: 2, level: 14, min: 121, max: 121 },
        { rank: 3, level: 20, min: 198, max: 198 },
        { rank: 4, level: 24, min: 286, max: 286 },
      ],
      dotRanges: [
        { rank: 1, level: 8, value: 11, duration: 6 },
        { rank: 2, level: 14, value: 20, duration: 6 },
        { rank: 3, level: 20, value: 33, duration: 6 },
        { rank: 4, level: 24, value: 48, duration: 6 },
      ],
      spendsShards: true,
      shardCost: 1,
    },
    {
      id: 'drain_life',
      name: 'Drain Life',
      icon: '🩸',
      iconImg: 'img/abilities/warlock/Spell_Shadow_LifeDrain02.jpg',
      school: 'Oscuro',
      type: 'damage',
      requiredLevel: 12,
      damageType: 'magical',
      baseDamage: 35,
      spellPowerRatio: 0.57,
      costPct: 0.05,
      castType: 'instant',
      cooldown: 0,
      description: 'Drena la vida del enemigo causando danyo y curandote por el 50% del danyo.',
      tags: ['shadow', 'direct', 'lifesteal'],
      damageRanges: [
        { rank: 1, level: 12, min: 18, max: 25 },
        { rank: 2, level: 18, min: 28, max: 38 },
        { rank: 3, level: 24, min: 40, max: 55 },
      ],
      lifestealPct: 0.5,
    },
    {
      id: 'rain_of_fire',
      name: 'Rain of Fire',
      icon: '🌋',
      iconImg: 'img/abilities/warlock/Spell_Fire_FelRainOfFire.jpg',
      school: 'Fuego',
      type: 'damage',
      requiredLevel: 20,
      damageType: 'magical',
      baseDamage: 60,
      spellPowerRatio: 0.57,
      costPct: 0.2,
      castType: 'cast',
      cooldown: 0,
      description: 'Lluvia de fuego fel que danya a todos los enemigos en el area. Consume 5 Soul Shards.',
      tags: ['fire', 'aoe', 'direct'],
      damageRanges: [
        { rank: 1, level: 20, min: 132, max: 176 },
        { rank: 2, level: 24, min: 187, max: 242 },
      ],
      aoe: true,
      spendsShards: true,
      shardCost: 5,
    },
    {
      id: 'summon_imp',
      name: 'Summon Imp',
      icon: '👹',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SummonImp.jpg',
      school: 'Invocacion',
      type: 'utility',
      requiredLevel: 5,
      costPct: 0.15,
      castType: 'cast',
      cooldown: 0,
      description: 'Invoca un diablillo que ataca automaticamente con Firebolt cada turno.',
      tags: ['pet'],
      isPetSummon: 'imp',
    },
    {
      id: 'summon_voidwalker',
      name: 'Summon Voidwalker',
      icon: '🔵',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SummonVoidWalker.jpg',
      school: 'Invocacion',
      type: 'utility',
      requiredLevel: 10,
      costPct: 0.25,
      castType: 'cast',
      cooldown: 0,
      description: 'Invoca un abisario tanque con mucha vida. Ataca con sombra cada turno. Consume 1 Soul Shard.',
      tags: ['pet'],
      isPetSummon: 'voidwalker',
      spendsShards: true,
      shardCost: 1,
    },
    {
      id: 'summon_infernal',
      name: 'Summon Infernal',
      icon: '🔥',
      iconImg: 'img/capstones/warlock/sumon_infernal.jpg',
      school: 'Invocacion',
      type: 'utility',
      requiredLevel: 0,
      costPct: 0,
      castType: 'instant',
      cooldown: 5,
      description: 'Coste: 2 Soul Shards. Invoca un Infernal que aterriza causando daño de Fuego a todos los enemigos cercanos y aturdiendolos 1 turno. Lucha a tu lado durante 4 turnos sin sustituir a tu demonio actual. CD 5.',
      tags: ['fire', 'aoe'],
      spendsShards: true,
      shardCost: 2,
      aoe: true,
      damageRanges: [{ rank: 1, level: 24, min: 85, max: 135 }],
      spellPowerRatio: 0.57,
      stunDuration: 1,
      infernalTurns: 4,
      infernalMin: 30,
      infernalMax: 50,
      capstoneGate: 'summon_infernal',
    },
    {
      id: 'seed_of_corruption',
      name: 'Seed of Corruption',
      icon: '🌱',
      iconImg: 'img/capstones/warlock/seed_of_corruption.jpg',
      school: 'Oscuro',
      type: 'utility',
      requiredLevel: 0,
      costPct: 0.35,
      castType: 'instant',
      cooldown: 5,
      description: 'Coste: 35% de mana y 1 Soul Shard. Aplica un DoT propio potenciado (Seed of Corruption, +10% danyo) a todos los enemigos. El Master devuelve 1 Soul Shard por cada enemigo afectado (max 5). CD 5.',
      tags: ['dot', 'aoe'],
      spendsShards: true,
      shardCost: 1,
      capstoneGate: 'seed_of_corruption',
    },
    {
      id: 'demonic_sacrifice',
      name: 'Demonic Sacrifice',
      icon: '💀',
      iconImg: 'img/capstones/warlock/demonic_sacrifice.jpg',
      school: 'Demoniaco',
      type: 'utility',
      requiredLevel: 0,
      costPct: 0,
      castType: 'instant',
      cooldown: 5,
      description: 'Coste: 2 Soul Shards. Sacrificas tu demonio actual: Imp - Burning Soul (+20% Spell Power); Voidwalker - Void Fortitude (+25% vida maxima y escudo del 25%). El efecto dura toda la batalla y se pierde al invocar cualquier pet. CD 5.',
      tags: ['pet'],
      spendsShards: true,
      shardCost: 2,
      capstoneGate: 'demonic_sacrifice',
    },
    {
      id: 'unsummon_pet',
      name: 'Unsummon Pet',
      icon: '👋',
      iconImg: '',
      school: 'Invocacion',
      type: 'utility',
      requiredLevel: 5,
      costPct: 0,
      castType: 'instant',
      cooldown: 0,
      description: 'Desinvoca a tu pet activa.',
      tags: ['pet'],
    },
    {
      id: 'life_tap',
      name: 'Life Tap',
      icon: '💧',
      iconImg: 'img/abilities/warlock/Spell_Shadow_BurningSpirit.jpg',
      school: 'Oscuro',
      type: 'utility',
      requiredLevel: 2,
      costPct: 0,
      castType: 'instant',
      cooldown: 0,
      noGcd: true,
      description: 'Sacrifica vida para recuperar mana. No gasta accion.',
      tags: [],
      buffRanks: [
        { rank: 1, level: 2, value: 40 },
        { rank: 2, level: 10, value: 80 },
        { rank: 3, level: 18, value: 140 },
        { rank: 4, level: 24, value: 200 },
      ],
    },
    {
      id: 'healthstone',
      name: 'Healthstone',
      icon: '💎',
      iconImg: 'img/abilities/warlock/INV_Stone_04.jpg',
      school: 'Oscuro',
      type: 'heal',
      requiredLevel: 6,
      damageType: 'magical',
      baseDamage: 30,
      spellPowerRatio: 0.8,
      costPct: 0,
      castType: 'instant',
      cooldown: 6,
      description: 'Crea una piedra de salud que cura a un aliado. Consume 1 Soul Shard.',
      tags: [],
      damageRanges: [
        { rank: 1, level: 6, min: 60, max: 80 },
        { rank: 2, level: 12, min: 100, max: 130 },
        { rank: 3, level: 18, min: 160, max: 200 },
        { rank: 4, level: 24, min: 240, max: 300 },
      ],
      spendsShards: true,
      shardCost: 1,
    },
    {
      id: 'fel_armor',
      name: 'Fel Armor',
      icon: '🛡️',
      iconImg: 'img/abilities/warlock/Spell_Shadow_FelArmour.jpg',
      school: 'Demoniaco',
      type: 'utility',
      requiredLevel: 10,
      costPct: 0.08,
      castType: 'instant',
      cooldown: 0,
      description: 'Armadura demoniaca que otorga +10/20/30 Poder de Hechizo (flat).',
      tags: [],
      buffRanks: [
        { rank: 1, level: 10, value: 10 },
        { rank: 2, level: 18, value: 20 },
        { rank: 3, level: 24, value: 30 },
      ],
    },
    {
      id: 'imp_blood_bolt',
      name: 'Blood Boil',
      icon: '🩸',
      iconImg: 'img/abilities/warlock/Spell_Shadow_BloodBoil.jpg',
      school: 'Oscuro',
      type: 'utility',
      requiredLevel: 8,
      costPct: 0,
      castType: 'instant',
      cooldown: 6,
      description: 'Sangre hirviente: otorga +Aguante (Stamina) al grupo durante 6 turnos. Con Grimoire of Command, ademas el imp sacrifica un 10% de su vida por punto y lanza ese dano en area. Si su vida llega a 0, desaparece y no otorga el buff.',
      tags: ['pet'],
      petAbility: 'imp',
      buffRanks: [
        { rank: 1, level: 8, value: 5 },
        { rank: 2, level: 16, value: 10 },
        { rank: 3, level: 22, value: 15 },
      ],
      partyBuff: true,
    },
    {
      id: 'voidwalker_taunt',
      name: 'Suffering',
      icon: '🗯️',
      iconImg: 'img/abilities/warlock/voidwalker_taunt.jpg',
      school: 'Físico',
      type: 'utility',
      requiredLevel: 12,
      costPct: 0,
      castType: 'instant',
      cooldown: 3,
      description: 'Suffering: obliga al enemigo a atacar al Voidwalker durante 2 turnos. Cuesta mana de la pet.',
      tags: ['pet'],
      petAbility: 'voidwalker',
      inflictsEffects: [{ type: 'debuff', name: 'Suffering', target: 'taunt', value: 0, duration: 2, debuffType: 'none' }],
    },
  ],

  pets: [
    {
      id: 'imp',
      name: 'Imp',
      icon: '👹',
      iconImg: 'img/abilities/warlock/ability_warlock_impoweredimp.jpg',
      requiredLevel: 5,
      hpPct: 0.3,
      manaPct: 0.3,
      attackName: 'Firebolt',
      attackMin: 15,
      attackMax: 25,
      attackSchool: 'Fuego',
      manaCostPct: 0.1,
    },
    {
      id: 'voidwalker',
      name: 'Voidwalker',
      icon: '🔵',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SummonVoidWalker.jpg',
      requiredLevel: 10,
      hpPct: 0.6,
      manaPct: 0.15,
      attackName: 'Torment',
      attackMin: 10,
      attackMax: 18,
      attackSchool: 'Oscuro',
      manaCostPct: 0.05,
    },
  ],
  hooks: WARLOCK_HOOKS,
};
