import type { ClassSpec } from '../../engine/types';
import { MAGE_HOOKS } from './mage-hooks';

export const MAGE: ClassSpec = {
  key: 'mage',
  name: 'Mage',
  color: '#3FC7EB',
  icon: '🔥',
  iconImg: 'img/classes/mage.jpg',

  formulas: {
    hp: (s, lvl) => 30 + s.aguante * 8 + lvl * 4,
    mana: (s, lvl) => 50 + s.intelecto * 15 + lvl * 5,
    spellPower: s => Math.round(s.intelecto * 0.65),
    attackPower: () => 0,
    manaRegen: s => Math.round(s.espiritu * 0.25 + 15),
  },

  baseStats: { fuerza: 3, agilidad: 3, intelecto: 20, aguante: 14, espiritu: 18 },
  startingLevel: 1,
  statGrowth: { fuerza: 0.1, agilidad: 0.1, intelecto: 2.0, aguante: 0.7, espiritu: 1.1 },
  armor: 4,
  magicResist: 5,

  resource: { type: 'mana', label: 'Maná', color: '#3498db', start: 'full' },

  talents: [
    {
      id: 'elemental_mastery',
      name: 'Elemental Mastery',
      icon: '🔥',
      iconImg: 'img/talents/mage/elemental_mastery.jpg',
      description: 'Aumenta el daño de todos tus hechizos un 2,5% por punto.',
      maxRank: 4,
      tier: 1,
      requires: null,
      modifiers: [{ target: '*', stat: 'damage', type: 'pct', valuePerRank: 2.5 }],
    },
    {
      id: 'combat_snacks',
      name: 'Combat Snacks',
      icon: '🍖',
      iconImg: 'img/talents/mage/combat_snacks.jpg',
      description: 'Al final de tu turno regeneras un 0,5% de tu vida máxima y un 1,5% de tu maná máximo por punto.',
      maxRank: 3,
      tier: 1,
      requires: null,
      modifiers: [],
    },
    {
      id: 'improved_frostbolt',
      name: 'Improved Frostbolt',
      icon: '❄️',
      iconImg: 'img/abilities/mage/frostbolt.jpg',
      description: 'Aumenta el daño de Frostbolt un 10% por punto.',
      maxRank: 3,
      tier: 1,
      requires: null,
      modifiers: [{ target: 'ability:frostbolt', stat: 'damage', type: 'pct', valuePerRank: 10 }],
    },
    {
      id: 'ignite',
      name: 'Ignite',
      icon: '🔥',
      iconImg: 'img/talents/mage/ignite.jpg',
      description: 'Un golpe critico con un hechizo de Fuego prende un DoT ardiente del 8% del daño por punto durante 3 turnos. Los Ignites se apilan como DoTs independientes.',
      maxRank: 3,
      tier: 1,
      requires: null,
      modifiers: [],
    },
    {
      id: 'improved_arcane_intellect',
      name: 'Improved Arcane Intellect',
      icon: '🧠',
      iconImg: 'img/abilities/mage/arcane_intellect.jpg',
      description: 'Aumenta el efecto de Arcane Intellect un 15% por punto.',
      maxRank: 2,
      tier: 2,
      requires: null,
      modifiers: [],
    },
    {
      id: 'improved_frost_armor',
      name: 'Improved Frost Armor',
      icon: '🧊',
      iconImg: 'img/abilities/mage/frost_armor.jpg',
      description: 'Aumenta el efecto de Frost Armor un 15% por punto.',
      maxRank: 2,
      tier: 2,
      requires: null,
      modifiers: [],
    },
    {
      id: 'improved_mana_gem',
      name: 'Improved Mana Gem',
      icon: '💎',
      iconImg: 'img/abilities/mage/mana_gem.jpg',
      description: 'Aumenta el maná que restaura Mana Gem un 25% por punto.',
      maxRank: 2,
      tier: 2,
      requires: null,
      modifiers: [],
    },
    {
      id: 'casting_master',
      name: 'Casting Master',
      icon: '📜',
      iconImg: 'img/talents/mage/casting_master.jpg',
      description: 'Aumenta el daño de todos tus hechizos con tiempo de lanzamiento un 5% por punto, y reduce su coste de maná un 5% por punto.',
      maxRank: 3,
      tier: 2,
      requires: null,
      modifiers: [
        { target: 'ability:fireball|frostbolt', stat: 'damage', type: 'pct', valuePerRank: 5 },
        { target: 'ability:fireball|frostbolt', stat: 'manaCost', type: 'pct', valuePerRank: -5 },
      ],
    },
    {
      id: 'magic_resistance',
      name: 'Magic Resistance',
      icon: '🛡️',
      iconImg: 'img/talents/mage/magic_resistance.jpg',
      description: 'Aumenta tu armadura mágica +5 por punto y tu probabilidad de crítico con hechizos instantáneos un 2% por punto.',
      maxRank: 3,
      tier: 2,
      requires: null,
      modifiers: [
        { target: 'ability:fire_blast|arcane_missiles|cone_of_cold|arcane_explosion|blast_wave', stat: 'critChance', type: 'flat', valuePerRank: 2 },
      ],
    },
    {
      id: 'improved_fire_blast',
      name: 'Improved Fire Blast',
      icon: '💥',
      iconImg: 'img/abilities/mage/fire_blast.jpg',
      description: 'Reduce el cooldown de Fire Blast 1 turno por punto y aumenta su probabilidad de crítico un 10% por punto.',
      maxRank: 2,
      tier: 3,
      requires: null,
      modifiers: [{ target: 'ability:fire_blast', stat: 'critChance', type: 'flat', valuePerRank: 10 }],
    },
    {
      id: 'frost_power',
      name: 'Frost Power',
      icon: '❄️',
      iconImg: 'img/talents/mage/frost_power.jpg',
      description: 'Aumenta la probabilidad de crítico de tus hechizos de Escarcha un 2% por punto y su daño crítico un 10% por punto.',
      maxRank: 3,
      tier: 3,
      requires: null,
      modifiers: [
        { target: 'ability:frostbolt|cone_of_cold', stat: 'critChance', type: 'flat', valuePerRank: 2 },
        { target: 'ability:frostbolt|cone_of_cold', stat: 'critDamage', type: 'pct', valuePerRank: 10 },
      ],
    },
    {
      id: 'improved_cone_of_cold',
      name: 'Improved Cone of Cold',
      icon: '🌬️',
      iconImg: 'img/abilities/mage/cone_of_cold.jpg',
      description: 'Reduce el cooldown de Cone of Cold 1 turno por punto y aumenta su daño un 15% por punto.',
      maxRank: 2,
      tier: 3,
      requires: null,
      modifiers: [{ target: 'ability:cone_of_cold', stat: 'damage', type: 'pct', valuePerRank: 15 }],
    },
    {
      id: 'arcane_torrent',
      name: 'Arcane Torrent',
      icon: '⚡',
      iconImg: 'img/talents/mage/arcane_torrent.jpg',
      description: 'Aumenta el daño y el coste de maná de Arcane Missiles y Arcane Explosion un 15% por punto.',
      maxRank: 3,
      tier: 3,
      requires: null,
      modifiers: [
        { target: 'ability:arcane_missiles|arcane_explosion', stat: 'damage', type: 'pct', valuePerRank: 15 },
        { target: 'ability:arcane_missiles|arcane_explosion', stat: 'manaCost', type: 'pct', valuePerRank: 15 },
      ],
    },
    {
      id: 'clearcasting',
      name: 'Clearcasting',
      icon: '🔮',
      iconImg: 'img/talents/mage/clearcasting.jpg',
      description: 'Tus hechizos tienen un 2,5% de probabilidad por punto de ser gratuitos al lanzarlos.',
      maxRank: 4,
      tier: 3,
      requires: null,
      modifiers: [],
    },
  ],

  capstones: [
    { id: 'combustion', name: 'Combustion', icon: '🔥', iconImg: 'img/capstones/mage/combustion.jpg', description: 'Durante 3 turnos, tus hechizos de Fuego tienen un 50% adicional de probabilidad de crítico y el efecto de tus Orbes de Fuego se duplica (+10% de daño crítico por orbe en lugar de +5%), ganando también un bono de daño crítico. CD 8.' },
    { id: 'icy_veins', name: 'Icy Veins', icon: '🧊', iconImg: 'img/capstones/mage/icy_veins.jpg', description: 'Durante 2 turnos, tus hechizos de Escarcha se lanzan de forma instantánea y solo consumen un punto de acción.' },
    { id: 'arcane_power', name: 'Arcane Power', icon: '⚡', iconImg: 'img/capstones/mage/arcane_power.jpg', description: 'Durante 2 turnos, tus hechizos cuestan un 50% menos de mana, tu Spell Power aumenta un 20% y tu danyo critico un 25%. Al final de cada turno recuperas un 20% de tu mana maximo. CD 6.' },
  ],

  abilities: [
    {
      id: 'fireball',
      name: 'Fireball',
      icon: '🔥',
      iconImg: 'img/abilities/mage/fireball.jpg',
      school: 'Fuego',
      type: 'damage',
      requiredLevel: 1,
      damageType: 'magical',
      baseDamage: 60,
      spellPowerRatio: 1.0,
      costPct: 0.0909,
      castType: 'cast',
      cooldown: 0,
      description: 'Lanza una bola de fuego que explota al impactar.',
      tags: ['fire', 'direct'],
      damageRanges: [
        { rank: 1, level: 1, min: 14, max: 22 },
        { rank: 2, level: 6, min: 31, max: 45 },
        { rank: 3, level: 12, min: 53, max: 73 },
        { rank: 4, level: 18, min: 104, max: 166 },
        { rank: 5, level: 24, min: 165, max: 265 },
      ],
    },
    {
      id: 'fire_blast',
      name: 'Fire Blast',
      icon: '💥',
      iconImg: 'img/abilities/mage/fire_blast.jpg',
      school: 'Fuego',
      type: 'damage',
      requiredLevel: 4,
      damageType: 'magical',
      baseDamage: 35,
      spellPowerRatio: 0.8,
      costPct: 0.0505,
      castType: 'instant',
      cooldown: 3,
      description: 'Una explosión instantánea de llamas al objetivo.',
      tags: ['fire', 'direct'],
      damageRanges: [
        { rank: 1, level: 4, min: 16, max: 26 },
        { rank: 2, level: 10, min: 30, max: 50 },
        { rank: 3, level: 16, min: 56, max: 90 },
        { rank: 4, level: 22, min: 99, max: 159 },
      ],
    },
    {
      id: 'frostbolt',
      name: 'Frostbolt',
      icon: '❄️',
      iconImg: 'img/abilities/mage/frostbolt.jpg',
      school: 'Escarcha',
      type: 'damage',
      requiredLevel: 6,
      damageType: 'magical',
      baseDamage: 45,
      spellPowerRatio: 1.0,
      costPct: 0.0808,
      castType: 'cast',
      cooldown: 0,
      description: 'Lanza un proyectil de hielo que ralentiza al objetivo.',
      tags: ['direct'],
      damageRanges: [
        { rank: 1, level: 6, min: 22, max: 26 },
        { rank: 2, level: 12, min: 37, max: 43 },
        { rank: 3, level: 18, min: 63, max: 73 },
        { rank: 4, level: 24, min: 104, max: 120 },
      ],
    },
    {
      id: 'arcane_missiles',
      name: 'Arcane Missiles',
      icon: '✨',
      iconImg: 'img/abilities/mage/arcane_missiles.jpg',
      school: 'Arcano',
      type: 'damage',
      requiredLevel: 14,
      damageType: 'magical',
      baseDamage: 100,
      spellPowerRatio: 0.8,
      costPct: 0.1515,
      castType: 'instant',
      cooldown: 1,
      description: 'Dispara misiles de energía arcana al objetivo.',
      tags: ['direct'],
      damageRanges: [
        { rank: 1, level: 14, min: 55, max: 73 },
        { rank: 2, level: 20, min: 97, max: 127 },
        { rank: 3, level: 26, min: 159, max: 209 },
      ],
    },
    {
      id: 'cone_of_cold',
      name: 'Cone of Cold',
      icon: '🌬️',
      iconImg: 'img/abilities/mage/cone_of_cold.jpg',
      school: 'Escarcha',
      type: 'damage',
      requiredLevel: 20,
      damageType: 'magical',
      baseDamage: 50,
      spellPowerRatio: 0.57,
      costPct: 0.0808,
      castType: 'instant',
      cooldown: 6,
      aoe: true,
      description: 'Cono de hielo instantaneo que danya y ralentiza a todos los enemigos frontales.',
      tags: ['aoe', 'direct'],
      damageRanges: [
        { rank: 1, level: 20, min: 90, max: 115 },
        { rank: 2, level: 28, min: 145, max: 180 },
        { rank: 3, level: 36, min: 220, max: 270 },
      ],
    },
    {
      id: 'arcane_explosion',
      name: 'Arcane Explosion',
      icon: '🔮',
      iconImg: 'img/abilities/mage/arcane_explosion.jpg',
      school: 'Arcano',
      type: 'damage',
      requiredLevel: 18,
      damageType: 'magical',
      baseDamage: 30,
      spellPowerRatio: 0.57,
      costPct: 0.18,
      castType: 'instant',
      cooldown: 0,
      aoe: true,
      description: 'Estalla energía arcana alrededor del mago dañando a todos los enemigos cercanos.',
      tags: ['aoe', 'direct'],
      damageRanges: [
        { rank: 1, level: 18, min: 70, max: 85 },
        { rank: 2, level: 24, min: 115, max: 140 },
      ],
    },
    {
      id: 'blast_wave',
      name: 'Blast Wave',
      icon: '🌋',
      iconImg: 'img/abilities/mage/blast_wave.jpg',
      school: 'Fuego',
      type: 'damage',
      requiredLevel: 24,
      damageType: 'magical',
      baseDamage: 60,
      spellPowerRatio: 0.57,
      costPct: 0.101,
      castType: 'instant',
      cooldown: 8,
      aoe: true,
      description: 'Onda expansiva de fuego instantanea que danya y empuja a todos los enemigos cercanos.',
      tags: ['fire', 'aoe', 'direct'],
      damageRanges: [
        { rank: 1, level: 24, min: 144, max: 180 },
        { rank: 2, level: 32, min: 225, max: 279 },
      ],
    },
    {
      id: 'combustion',
      name: 'Combustion',
      icon: '🔥',
      iconImg: 'img/capstones/mage/combustion.jpg',
      school: 'Fuego',
      type: 'utility',
      requiredLevel: 1,
      costPct: 0,
      castType: 'instant',
      cooldown: 8,
      noGcd: true,
      description: 'Durante 3 turnos, tus hechizos de Fuego tienen un 50% adicional de probabilidad de crítico y el efecto de tus Orbes de Fuego se duplica (+10% de daño crítico por orbe en lugar de +5%), ganando también un bono de daño crítico. CD 8.',
      buff: null,
      capstoneGate: 'combustion',
    },
    {
      id: 'icy_veins',
      name: 'Icy Veins',
      icon: '🧊',
      iconImg: 'img/capstones/mage/icy_veins.jpg',
      school: 'Escarcha',
      type: 'utility',
      requiredLevel: 1,
      costPct: 0,
      castType: 'instant',
      cooldown: 6,
      noGcd: true,
      description: 'Durante 2 turnos, tus hechizos de Escarcha se lanzan de forma instantanea y solo consumen un punto de accion. CD 6.',
      buff: null,
      capstoneGate: 'icy_veins',
    },
    {
      id: 'arcane_power',
      name: 'Arcane Power',
      icon: '⚡',
      iconImg: 'img/capstones/mage/arcane_power.jpg',
      school: 'Arcano',
      type: 'utility',
      requiredLevel: 1,
      costPct: 0,
      castType: 'instant',
      cooldown: 6,
      noGcd: true,
      description: 'Durante 2 turnos, tus hechizos cuestan un 50% menos de mana, tu Spell Power aumenta un 20% y tu danyo critico un 25%. Al final de cada turno recuperas un 20% de tu mana maximo. CD 6.',
      buff: null,
      capstoneGate: 'arcane_power',
    },
    {
      id: 'arcane_intellect',
      name: 'Arcane Intellect',
      icon: '🧠',
      iconImg: 'img/abilities/mage/arcane_intellect.jpg',
      school: 'Arcano',
      type: 'utility',
      requiredLevel: 1,
      costPct: 0.0606,
      castType: 'instant',
      cooldown: 0,
      description: 'Aumenta el Intelecto del objetivo.',
      buff: { stat: 'intelecto', duration: 30 },
      buffRanks: [
        { rank: 1, level: 1, value: 2, costPct: 0.0606 },
        { rank: 2, level: 14, value: 7, costPct: 0.0707 },
        { rank: 3, level: 28, value: 10, costPct: 0.0808 },
        { rank: 4, level: 42, value: 15, costPct: 0.0909 },
        { rank: 5, level: 56, value: 20, costPct: 0.101 },
      ],
    },
    {
      id: 'frost_armor',
      name: 'Frost Armor',
      icon: '🧊',
      iconImg: 'img/abilities/mage/frost_armor.jpg',
      school: 'Escarcha',
      type: 'utility',
      requiredLevel: 4,
      costPct: 0.303,
      castType: 'instant',
      cooldown: 0,
      description: 'Crea una barrera de hielo que aumenta tu armadura física.',
      buff: { stat: 'armor', duration: 30, applySelf: true },
      buffRanks: [
        { rank: 1, level: 4, value: 15, costPct: 0.303 },
        { rank: 2, level: 14, value: 22, costPct: 0.303 },
        { rank: 3, level: 24, value: 32, costPct: 0.303 },
        { rank: 4, level: 34, value: 45, costPct: 0.303 },
        { rank: 5, level: 44, value: 60, costPct: 0.303 },
        { rank: 6, level: 54, value: 80, costPct: 0.303 },
      ],
    },
    {
      id: 'mana_gem',
      name: 'Mana Gem',
      icon: '💎',
      iconImg: 'img/abilities/mage/mana_gem.jpg',
      school: 'Arcano',
      type: 'utility',
      requiredLevel: 8,
      costPct: 0,
      castType: 'instant',
      cooldown: 5,
      description: 'Conjura y consume una gema que restaura una cantidad plana de maná. El maná restaurado crece con cada rango. CD 5.',
      manaGemRanks: [
        { rank: 1, level: 8, value: 200 },
        { rank: 2, level: 16, value: 330 },
        { rank: 3, level: 24, value: 470 },
        { rank: 4, level: 32, value: 620 },
        { rank: 5, level: 40, value: 780 },
        { rank: 6, level: 48, value: 950 },
      ],
    },
    {
      id: 'blink',
      name: 'Blink',
      icon: '💨',
      iconImg: 'img/abilities/mage/blink.jpg',
      school: 'Arcano',
      type: 'utility',
      requiredLevel: 15,
      costPct: 0.101,
      castType: 'instant',
      cooldown: 4,
      noGcd: true,
      description: 'Te teletransportas instantáneamente, escapando de efectos de control.',
      buff: null,
    },
    {
      id: 'remove_curse',
      name: 'Remove Curse',
      icon: '✨',
      iconImg: 'img/abilities/mage/remove_curse.jpg',
      school: 'Arcano',
      type: 'utility',
      requiredLevel: 12,
      costPct: 0.0505,
      castType: 'instant',
      cooldown: 0,
      description: 'Elimina una maldicion del objetivo.',
      bonusPerRank: [0, 0, 0],
    },
    {
      id: 'elemental_orbs',
      name: 'Elemental Orbs',
      icon: '🔮',
      iconImg: 'img/abilities/mage/elemental_orbs.jpg',
      school: 'Pasiva',
      type: 'utility',
      requiredLevel: 10,
      costPct: 0,
      castType: 'instant',
      cooldown: 0,
      passive: true,
      description: 'Pasiva aprendida al nivel 10: tus hechizos de Fuego, Escarcha y Arcano generan Orbes Elementales (máximo 3) en la barra bajo tu maná.',
    },
  ],

  pets: [],
  hooks: MAGE_HOOKS,
};
